name: Github Actions feirinha_backend
run-name: ${{ github.actor }} is running GitHub Actions 🚀
on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
jobs:
  Run-Test:
    runs-on: ubuntu-latest
    steps:
    - run: echo "test!!!"
